version: '3.6'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "123456"

  api:
    build: .
    command: |
      bash -c "bash ./wait-for-it.sh db:5432 -q -- \
      echo $${DATABASE_URL}
      diesel setup
      hero_api"
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "123456"
      DATABASE_URL: postgres://postgres_user:123456@db:5432/postgres_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 7897:8080
